# Generated by Django 4.1.5 on 2023-02-01 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('coingecko_id', models.CharField(max_length=100, null=True)),
                ('coinmarketcap_id', models.CharField(max_length=100, null=True)),
                ('price', models.CharField(max_length=10, null=True)),
                ('market_cap', models.IntegerField(null=True)),
                ('fdv', models.IntegerField(null=True)),
                ('volume', models.IntegerField(null=True)),
                ('twitter_id', models.CharField(max_length=15, null=True)),
                ('twitter_score', models.IntegerField(null=True)),
                ('coefficient_mc', models.FloatField(null=True)),
                ('coefficient_fdv', models.FloatField(null=True)),
                ('site', models.CharField(max_length=200, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'all_crypto',
            },
        ),
    ]
