# Generated by Django 4.1.5 on 2023-02-01 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaemonModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coins_update_status', models.BooleanField()),
                ('coins_total_updated', models.IntegerField(default=0)),
                ('coins_current_update', models.CharField(blank=True, default='', max_length=15)),
                ('score_update_status', models.BooleanField()),
                ('score_total_updated', models.IntegerField(default=0)),
                ('score_current_update', models.CharField(blank=True, default='', max_length=15)),
            ],
            options={
                'db_table': 'daemon_service',
            },
        ),
    ]
