# Generated by Django 4.1.5 on 2023-02-03 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webstat', '0003_daemonmodel_coins_message_daemonmodel_score_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptomodel',
            name='coefficient_fdv',
        ),
        migrations.RemoveField(
            model_name='cryptomodel',
            name='coefficient_mc',
        ),
    ]
