# Generated by Django 4.1.5 on 2023-03-30 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webstat', '0004_remove_cryptomodel_coefficient_fdv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptomodel',
            name='twitter_score_changes',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
